from tkinter import *
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

import unknown_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    unknown_support.set_Tk_var()
    top = Toplevel1(root)
    unknown_support.init(root, top)
    root.mainloop()


w = None


def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    unknown_support.set_Tk_var()
    top = Toplevel1(w)
    unknown_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.', background=_bgcolor)
        self.style.configure('.', foreground=_fgcolor)
        self.style.configure('.', font="TkDefaultFont")
        self.style.map('.', background=
        [('selected', _compcolor), ('active', _ana2color)])

        top.geometry("1032x754+478+139")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("CUCKS GUI")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
        [('selected', _compcolor), ('active', _ana2color)])
        self.TNotebook1 = ttk.Notebook(top)
        self.TNotebook1.place(relx=0.0, rely=0.0, relheight=0.989
                              , relwidth=1.002)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_t0 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t0, padding=3)
        self.TNotebook1.tab(0, text="Dashboard", compound="left", underline="-1"
                            , )
        self.TNotebook1_t0.configure(background="#d9d9d9")
        self.TNotebook1_t0.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t0.configure(highlightcolor="black")
        self.TNotebook1_t1 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t1, padding=3)
        self.TNotebook1.tab(1, text="Graph", compound="left", underline="-1", )
        self.TNotebook1_t1.configure(background="#d9d9d9")
        self.TNotebook1_t1.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t1.configure(highlightcolor="black")
        self.TNotebook1_t2 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t2, padding=3)
        self.TNotebook1.tab(2, text="Config", compound="none", underline="-1", )
        self.TNotebook1_t2.configure(background="#d9d9d9")
        self.TNotebook1_t2.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t2.configure(highlightcolor="black")
        self.TNotebook1_t3 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t3, padding=3)
        self.TNotebook1.tab(3, text="Help", compound="none", underline="-1", )
        self.TNotebook1_t3.configure(background="#d9d9d9")
        self.TNotebook1_t3.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t3.configure(highlightcolor="black")

        self.Canvas1 = tk.Canvas(self.TNotebook1_t0)
        self.Canvas1.place(relx=0.291, rely=0.264, relheight=0.699
                           , relwidth=0.68)
        self.Canvas1.configure(background="#d9d9d9")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="black")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.create_line(50, 550, 1150, 550, width=2)  # x-axis dikke lijn
        self.Canvas1.create_text(600, 575, text='Step')  # ik weet niet welke tekst hier moet
        self.Canvas1.create_line(50, 550, 50, 50, width=2)  # y-axis dikke lijn
        self.Canvas1.create_text(18, 275,
                                 text='Value')  # Ziet er echt super slordig uit maar ik weet niet hoe ik die text opzij kan
        # flippen dus hij ziet hier maar ietsje lelijk erbij

        # x-axis
        for i in range(23):
            x = 50 + (i * 50)
            self.Canvas1.create_line(x, 550, x, 50, width=1, dash=(2, 5))
            self.Canvas1.create_text(x, 550, text='%d' % (10 * i), anchor=N)

        # y-axis
        for i in range(11):
            y = 550 - (i * 50)
            self.Canvas1.create_line(50, y, 1150, y, width=1, dash=(2, 5))
            self.Canvas1.create_text(40, y, text='%d' % (10 * i), anchor=E)

        self.Button1 = tk.Button(self.TNotebook1_t0)
        self.Button1.place(relx=0.01, rely=0.778, height=54, width=277)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''OPEN SCHERM''')

        self.Button23 = tk.Button(self.TNotebook1_t0)
        self.Button23.place(relx=0.01, rely=0.875, height=54, width=277)
        self.Button23.configure(activebackground="#ececec")
        self.Button23.configure(activeforeground="#000000")
        self.Button23.configure(background="#d9d9d9")
        self.Button23.configure(disabledforeground="#a3a3a3")
        self.Button23.configure(foreground="#000000")
        self.Button23.configure(highlightbackground="#d9d9d9")
        self.Button23.configure(highlightcolor="black")
        self.Button23.configure(pady="0")
        self.Button23.configure(text='''CLOSE SCHERM''')

        self.Listbox1 = tk.Listbox(self.TNotebook1_t0)
        self.Listbox1.place(relx=0.01, rely=0.014, relheight=0.239
                            , relwidth=0.272)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.configure(highlightbackground="#d9d9d9")
        self.Listbox1.configure(highlightcolor="black")
        self.Listbox1.configure(selectbackground="#c4c4c4")
        self.Listbox1.configure(selectforeground="black")

        self.TNotebook2 = ttk.Notebook(self.TNotebook1_t0)
        self.TNotebook2.place(relx=0.291, rely=0.014, relheight=0.244
                              , relwidth=0.68)
        self.TNotebook2.configure(takefocus="")
        self.TNotebook2_t0 = tk.Frame(self.TNotebook2)
        self.TNotebook2.add(self.TNotebook2_t0, padding=3)
        self.TNotebook2.tab(0, text="Afstandsensor", compound="left"
                            , underline="-1", )
        self.TNotebook2_t0.configure(background="#d9d9d9")
        self.TNotebook2_t0.configure(highlightbackground="#d9d9d9")
        self.TNotebook2_t0.configure(highlightcolor="black")
        self.TNotebook2_t1 = tk.Frame(self.TNotebook2)
        self.TNotebook2.add(self.TNotebook2_t1, padding=3)
        self.TNotebook2.tab(1, text="Lichtsensor", compound="left", underline="-1"
                            , )
        self.TNotebook2_t1.configure(background="#d9d9d9")
        self.TNotebook2_t1.configure(highlightbackground="#d9d9d9")
        self.TNotebook2_t1.configure(highlightcolor="black")
        self.TNotebook2_t2 = tk.Frame(self.TNotebook2)
        self.TNotebook2.add(self.TNotebook2_t2, padding=3)
        self.TNotebook2.tab(2, text="Temperatuur", compound="none", underline="-1"
                            , )
        self.TNotebook2_t2.configure(background="#d9d9d9")
        self.TNotebook2_t2.configure(highlightbackground="#d9d9d9")
        self.TNotebook2_t2.configure(highlightcolor="black")

        self.Listbox2 = tk.Listbox(self.TNotebook1_t0)
        self.Listbox2.place(relx=0.01, rely=0.264, relheight=0.239
                            , relwidth=0.272)
        self.Listbox2.configure(background="white")
        self.Listbox2.configure(disabledforeground="#a3a3a3")
        self.Listbox2.configure(font="TkFixedFont")
        self.Listbox2.configure(foreground="#000000")
        self.Listbox2.configure(highlightbackground="#d9d9d9")
        self.Listbox2.configure(highlightcolor="black")
        self.Listbox2.configure(selectbackground="#c4c4c4")
        self.Listbox2.configure(selectforeground="black")

        self.Listbox3 = tk.Listbox(self.TNotebook1_t0)
        self.Listbox3.place(relx=0.01, rely=0.514, relheight=0.239
                            , relwidth=0.272)
        self.Listbox3.configure(background="white")
        self.Listbox3.configure(disabledforeground="#a3a3a3")
        self.Listbox3.configure(font="TkFixedFont")
        self.Listbox3.configure(foreground="#000000")
        self.Listbox3.configure(highlightbackground="#d9d9d9")
        self.Listbox3.configure(highlightcolor="black")
        self.Listbox3.configure(selectbackground="#c4c4c4")
        self.Listbox3.configure(selectforeground="black")

        self.TNotebook3 = ttk.Notebook(self.TNotebook1_t1)
        self.TNotebook3.place(relx=0.01, rely=0.014, relheight=0.967
                              , relwidth=0.975)
        self.TNotebook3.configure(takefocus="")
        self.TNotebook3_t0 = tk.Frame(self.TNotebook3)
        self.TNotebook3.add(self.TNotebook3_t0, padding=3)
        self.TNotebook3.tab(0, text="Licht", compound="left", underline="-1", )
        self.TNotebook3_t0.configure(background="#d9d9d9")
        self.TNotebook3_t0.configure(highlightbackground="#d9d9d9")
        self.TNotebook3_t0.configure(highlightcolor="black")
        self.TNotebook3_t1 = tk.Frame(self.TNotebook3)
        self.TNotebook3.add(self.TNotebook3_t1, padding=3)
        self.TNotebook3.tab(1, text="Temperatuur", compound="left", underline="-1"
                            , )
        self.TNotebook3_t1.configure(background="#d9d9d9")
        self.TNotebook3_t1.configure(highlightbackground="#d9d9d9")
        self.TNotebook3_t1.configure(highlightcolor="black")
        self.TNotebook3_t2 = tk.Frame(self.TNotebook3)
        self.TNotebook3.add(self.TNotebook3_t2, padding=3)
        self.TNotebook3.tab(2, text="Afstand", compound="none", underline="-1", )
        self.TNotebook3_t2.configure(background="#d9d9d9")
        self.TNotebook3_t2.configure(highlightbackground="#d9d9d9")
        self.TNotebook3_t2.configure(highlightcolor="black")

        self.Canvas2 = tk.Canvas(self.TNotebook3_t0)
        self.Canvas2.place(relx=0.0, rely=0.0, relheight=1.004, relwidth=1.003)
        self.Canvas2.configure(background="#d9d9d9")
        self.Canvas2.configure(borderwidth="2")
        self.Canvas2.configure(highlightbackground="#d9d9d9")
        self.Canvas2.configure(highlightcolor="black")
        self.Canvas2.configure(insertbackground="black")
        self.Canvas2.configure(relief="ridge")
        self.Canvas2.configure(selectbackground="#c4c4c4")
        self.Canvas2.configure(selectforeground="black")

        self.Canvas3 = tk.Canvas(self.TNotebook3_t1)
        self.Canvas3.place(relx=0.0, rely=0.0, relheight=1.004, relwidth=1.013)
        self.Canvas3.configure(background="#d9d9d9")
        self.Canvas3.configure(borderwidth="2")
        self.Canvas3.configure(highlightbackground="#d9d9d9")
        self.Canvas3.configure(highlightcolor="black")
        self.Canvas3.configure(insertbackground="black")
        self.Canvas3.configure(relief="ridge")
        self.Canvas3.configure(selectbackground="#c4c4c4")
        self.Canvas3.configure(selectforeground="black")

        self.Canvas4 = tk.Canvas(self.TNotebook3_t2)
        self.Canvas4.place(relx=0.0, rely=0.0, relheight=1.004, relwidth=1.003)
        self.Canvas4.configure(background="#d9d9d9")
        self.Canvas4.configure(borderwidth="2")
        self.Canvas4.configure(highlightbackground="#d9d9d9")
        self.Canvas4.configure(highlightcolor="black")
        self.Canvas4.configure(insertbackground="black")
        self.Canvas4.configure(relief="ridge")
        self.Canvas4.configure(selectbackground="#c4c4c4")
        self.Canvas4.configure(selectforeground="black")

        self.TNotebook4 = ttk.Notebook(self.TNotebook1_t2)
        self.TNotebook4.place(relx=0.0, rely=0.014, relheight=0.994
                              , relwidth=0.994)
        self.TNotebook4.configure(takefocus="")
        self.TNotebook4_t0 = tk.Frame(self.TNotebook4)
        self.TNotebook4.add(self.TNotebook4_t0, padding=3)
        self.TNotebook4.tab(0, text="Temperatuur", compound="left", underline="-1"
                            , )
        self.TNotebook4_t0.configure(background="#d9d9d9")
        self.TNotebook4_t0.configure(highlightbackground="#d9d9d9")
        self.TNotebook4_t0.configure(highlightcolor="black")
        self.TNotebook4_t1 = tk.Frame(self.TNotebook4)
        self.TNotebook4.add(self.TNotebook4_t1, padding=3)
        self.TNotebook4.tab(1, text="Licht", compound="left", underline="-1", )
        self.TNotebook4_t1.configure(background="#d9d9d9")
        self.TNotebook4_t1.configure(highlightbackground="#d9d9d9")
        self.TNotebook4_t1.configure(highlightcolor="black")
        self.TNotebook4_t2 = tk.Frame(self.TNotebook4)
        self.TNotebook4.add(self.TNotebook4_t2, padding=3)
        self.TNotebook4.tab(2, text="Afstand", compound="none", underline="-1", )
        self.TNotebook4_t2.configure(background="#d9d9d9")
        self.TNotebook4_t2.configure(highlightbackground="#d9d9d9")
        self.TNotebook4_t2.configure(highlightcolor="black")

        self.Entry1 = tk.Entry(self.TNotebook4_t0)
        self.Entry1.place(relx=0.088, rely=0.029, height=20, relwidth=0.161)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Entry2 = tk.Entry(self.TNotebook4_t0)
        self.Entry2.place(relx=0.088, rely=0.072, height=20, relwidth=0.161)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")

        self.Entry3 = tk.Entry(self.TNotebook4_t0)
        self.Entry3.place(relx=0.088, rely=0.116, height=20, relwidth=0.161)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")

        self.Entry4 = tk.Entry(self.TNotebook4_t0)
        self.Entry4.place(relx=0.088, rely=0.159, height=20, relwidth=0.161)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(highlightbackground="#d9d9d9")
        self.Entry4.configure(highlightcolor="black")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(selectforeground="black")

        self.Entry5 = tk.Entry(self.TNotebook4_t0)
        self.Entry5.place(relx=0.088, rely=0.203, height=20, relwidth=0.161)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(highlightbackground="#d9d9d9")
        self.Entry5.configure(highlightcolor="black")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(selectbackground="#c4c4c4")
        self.Entry5.configure(selectforeground="black")

        self.Entry6 = tk.Entry(self.TNotebook4_t0)
        self.Entry6.place(relx=0.088, rely=0.246, height=20, relwidth=0.161)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(highlightbackground="#d9d9d9")
        self.Entry6.configure(highlightcolor="black")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(selectbackground="#c4c4c4")
        self.Entry6.configure(selectforeground="black")

        self.Entry7 = tk.Entry(self.TNotebook4_t0)
        self.Entry7.place(relx=0.088, rely=0.29, height=20, relwidth=0.161)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(highlightbackground="#d9d9d9")
        self.Entry7.configure(highlightcolor="black")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(selectbackground="#c4c4c4")
        self.Entry7.configure(selectforeground="black")

        self.Entry8 = tk.Entry(self.TNotebook4_t0)
        self.Entry8.place(relx=0.088, rely=0.333, height=20, relwidth=0.161)
        self.Entry8.configure(background="white")
        self.Entry8.configure(disabledforeground="#a3a3a3")
        self.Entry8.configure(font="TkFixedFont")
        self.Entry8.configure(foreground="#000000")
        self.Entry8.configure(highlightbackground="#d9d9d9")
        self.Entry8.configure(highlightcolor="black")
        self.Entry8.configure(insertbackground="black")
        self.Entry8.configure(selectbackground="#c4c4c4")
        self.Entry8.configure(selectforeground="black")

        self.Label2 = tk.Label(self.TNotebook4_t0)
        self.Label2.place(relx=0.0, rely=0.029, height=21, width=74)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Setting''')

        self.Label2 = tk.Label(self.TNotebook4_t0)
        self.Label2.place(relx=0.0, rely=0.072, height=21, width=74)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Setting''')

        self.Label2 = tk.Label(self.TNotebook4_t0)
        self.Label2.place(relx=0.0, rely=0.116, height=21, width=74)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Setting''')

        self.Label2 = tk.Label(self.TNotebook4_t0)
        self.Label2.place(relx=0.0, rely=0.159, height=21, width=74)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Setting''')

        self.Label2 = tk.Label(self.TNotebook4_t0)
        self.Label2.place(relx=0.0, rely=0.203, height=21, width=74)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Setting''')

        self.Label2 = tk.Label(self.TNotebook4_t0)
        self.Label2.place(relx=0.0, rely=0.246, height=21, width=74)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Setting''')

        self.Label2 = tk.Label(self.TNotebook4_t0)
        self.Label2.place(relx=0.0, rely=0.29, height=21, width=74)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Setting''')

        self.Label2 = tk.Label(self.TNotebook4_t0)
        self.Label2.place(relx=0.0, rely=0.333, height=21, width=74)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Setting''')

        self.Button2 = tk.Button(self.TNotebook4_t0)
        self.Button2.place(relx=0.265, rely=0.029, height=24, width=47)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Set''')

        self.Button3 = tk.Button(self.TNotebook4_t0)
        self.Button3.place(relx=0.324, rely=0.029, height=24, width=37)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Reset''')

        self.Button4 = tk.Button(self.TNotebook4_t0)
        self.Button4.place(relx=0.324, rely=0.072, height=24, width=37)
        self.Button4.configure(activebackground="#ececec")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Reset''')

        self.Button5 = tk.Button(self.TNotebook4_t0)
        self.Button5.place(relx=0.324, rely=0.116, height=24, width=37)
        self.Button5.configure(activebackground="#ececec")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#d9d9d9")
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(text='''Reset''')

        self.Button6 = tk.Button(self.TNotebook4_t0)
        self.Button6.place(relx=0.324, rely=0.159, height=24, width=37)
        self.Button6.configure(activebackground="#ececec")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#d9d9d9")
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0")
        self.Button6.configure(text='''Reset''')

        self.Button7 = tk.Button(self.TNotebook4_t0)
        self.Button7.place(relx=0.324, rely=0.203, height=24, width=37)
        self.Button7.configure(activebackground="#ececec")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="#d9d9d9")
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(pady="0")
        self.Button7.configure(text='''Reset''')

        self.Button8 = tk.Button(self.TNotebook4_t0)
        self.Button8.place(relx=0.324, rely=0.246, height=24, width=37)
        self.Button8.configure(activebackground="#ececec")
        self.Button8.configure(activeforeground="#000000")
        self.Button8.configure(background="#d9d9d9")
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="black")
        self.Button8.configure(pady="0")
        self.Button8.configure(text='''Reset''')

        self.Button9 = tk.Button(self.TNotebook4_t0)
        self.Button9.place(relx=0.324, rely=0.29, height=24, width=37)
        self.Button9.configure(activebackground="#ececec")
        self.Button9.configure(activeforeground="#000000")
        self.Button9.configure(background="#d9d9d9")
        self.Button9.configure(disabledforeground="#a3a3a3")
        self.Button9.configure(foreground="#000000")
        self.Button9.configure(highlightbackground="#d9d9d9")
        self.Button9.configure(highlightcolor="black")
        self.Button9.configure(pady="0")
        self.Button9.configure(text='''Reset''')

        self.Button10 = tk.Button(self.TNotebook4_t0)
        self.Button10.place(relx=0.324, rely=0.333, height=24, width=37)
        self.Button10.configure(activebackground="#ececec")
        self.Button10.configure(activeforeground="#000000")
        self.Button10.configure(background="#d9d9d9")
        self.Button10.configure(disabledforeground="#a3a3a3")
        self.Button10.configure(foreground="#000000")
        self.Button10.configure(highlightbackground="#d9d9d9")
        self.Button10.configure(highlightcolor="black")
        self.Button10.configure(pady="0")
        self.Button10.configure(text='''Reset''')

        self.Button11 = tk.Button(self.TNotebook4_t0)
        self.Button11.place(relx=0.265, rely=0.072, height=24, width=47)
        self.Button11.configure(activebackground="#ececec")
        self.Button11.configure(activeforeground="#000000")
        self.Button11.configure(background="#d9d9d9")
        self.Button11.configure(disabledforeground="#a3a3a3")
        self.Button11.configure(foreground="#000000")
        self.Button11.configure(highlightbackground="#d9d9d9")
        self.Button11.configure(highlightcolor="black")
        self.Button11.configure(pady="0")
        self.Button11.configure(text='''Set''')

        self.Button12 = tk.Button(self.TNotebook4_t0)
        self.Button12.place(relx=0.265, rely=0.116, height=24, width=47)
        self.Button12.configure(activebackground="#ececec")
        self.Button12.configure(activeforeground="#000000")
        self.Button12.configure(background="#d9d9d9")
        self.Button12.configure(disabledforeground="#a3a3a3")
        self.Button12.configure(foreground="#000000")
        self.Button12.configure(highlightbackground="#d9d9d9")
        self.Button12.configure(highlightcolor="black")
        self.Button12.configure(pady="0")
        self.Button12.configure(text='''Set''')

        self.Button13 = tk.Button(self.TNotebook4_t0)
        self.Button13.place(relx=0.265, rely=0.159, height=24, width=47)
        self.Button13.configure(activebackground="#ececec")
        self.Button13.configure(activeforeground="#000000")
        self.Button13.configure(background="#d9d9d9")
        self.Button13.configure(disabledforeground="#a3a3a3")
        self.Button13.configure(foreground="#000000")
        self.Button13.configure(highlightbackground="#d9d9d9")
        self.Button13.configure(highlightcolor="black")
        self.Button13.configure(pady="0")
        self.Button13.configure(text='''Set''')

        self.Button14 = tk.Button(self.TNotebook4_t0)
        self.Button14.place(relx=0.265, rely=0.203, height=24, width=47)
        self.Button14.configure(activebackground="#ececec")
        self.Button14.configure(activeforeground="#000000")
        self.Button14.configure(background="#d9d9d9")
        self.Button14.configure(disabledforeground="#a3a3a3")
        self.Button14.configure(foreground="#000000")
        self.Button14.configure(highlightbackground="#d9d9d9")
        self.Button14.configure(highlightcolor="black")
        self.Button14.configure(pady="0")
        self.Button14.configure(text='''Set''')

        self.Button15 = tk.Button(self.TNotebook4_t0)
        self.Button15.place(relx=0.265, rely=0.246, height=24, width=47)
        self.Button15.configure(activebackground="#ececec")
        self.Button15.configure(activeforeground="#000000")
        self.Button15.configure(background="#d9d9d9")
        self.Button15.configure(disabledforeground="#a3a3a3")
        self.Button15.configure(foreground="#000000")
        self.Button15.configure(highlightbackground="#d9d9d9")
        self.Button15.configure(highlightcolor="black")
        self.Button15.configure(pady="0")
        self.Button15.configure(text='''Set''')

        self.Button16 = tk.Button(self.TNotebook4_t0)
        self.Button16.place(relx=0.265, rely=0.29, height=24, width=47)
        self.Button16.configure(activebackground="#ececec")
        self.Button16.configure(activeforeground="#000000")
        self.Button16.configure(background="#d9d9d9")
        self.Button16.configure(disabledforeground="#a3a3a3")
        self.Button16.configure(foreground="#000000")
        self.Button16.configure(highlightbackground="#d9d9d9")
        self.Button16.configure(highlightcolor="black")
        self.Button16.configure(pady="0")
        self.Button16.configure(text='''Set''')

        self.Button17 = tk.Button(self.TNotebook4_t0)
        self.Button17.place(relx=0.265, rely=0.333, height=24, width=47)
        self.Button17.configure(activebackground="#ececec")
        self.Button17.configure(activeforeground="#000000")
        self.Button17.configure(background="#d9d9d9")
        self.Button17.configure(disabledforeground="#a3a3a3")
        self.Button17.configure(foreground="#000000")
        self.Button17.configure(highlightbackground="#d9d9d9")
        self.Button17.configure(highlightcolor="black")
        self.Button17.configure(pady="0")
        self.Button17.configure(text='''Set''')

        self.Checkbutton1 = tk.Checkbutton(self.TNotebook4_t0)
        self.Checkbutton1.place(relx=0.088, rely=0.391, relheight=0.036
                                , relwidth=0.06)
        self.Checkbutton1.configure(activebackground="#ececec")
        self.Checkbutton1.configure(activeforeground="#000000")
        self.Checkbutton1.configure(background="#d9d9d9")
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(foreground="#000000")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify='left')
        self.Checkbutton1.configure(text='''Check''')
        self.Checkbutton1.configure(variable=unknown_support.che93)

        self.Checkbutton2 = tk.Checkbutton(self.TNotebook4_t0)
        self.Checkbutton2.place(relx=0.088, rely=0.435, relheight=0.036
                                , relwidth=0.06)
        self.Checkbutton2.configure(activebackground="#ececec")
        self.Checkbutton2.configure(activeforeground="#000000")
        self.Checkbutton2.configure(background="#d9d9d9")
        self.Checkbutton2.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2.configure(foreground="#000000")
        self.Checkbutton2.configure(highlightbackground="#d9d9d9")
        self.Checkbutton2.configure(highlightcolor="black")
        self.Checkbutton2.configure(justify='left')
        self.Checkbutton2.configure(text='''Check''')
        self.Checkbutton2.configure(variable=unknown_support.che94)

        self.Checkbutton3 = tk.Checkbutton(self.TNotebook4_t0)
        self.Checkbutton3.place(relx=0.088, rely=0.478, relheight=0.036
                                , relwidth=0.06)
        self.Checkbutton3.configure(activebackground="#ececec")
        self.Checkbutton3.configure(activeforeground="#000000")
        self.Checkbutton3.configure(background="#d9d9d9")
        self.Checkbutton3.configure(disabledforeground="#a3a3a3")
        self.Checkbutton3.configure(foreground="#000000")
        self.Checkbutton3.configure(highlightbackground="#d9d9d9")
        self.Checkbutton3.configure(highlightcolor="black")
        self.Checkbutton3.configure(justify='left')
        self.Checkbutton3.configure(text='''Check''')
        self.Checkbutton3.configure(variable=unknown_support.che95)

        self.Checkbutton4 = tk.Checkbutton(self.TNotebook4_t0)
        self.Checkbutton4.place(relx=0.157, rely=0.391, relheight=0.036
                                , relwidth=0.06)
        self.Checkbutton4.configure(activebackground="#ececec")
        self.Checkbutton4.configure(activeforeground="#000000")
        self.Checkbutton4.configure(background="#d9d9d9")
        self.Checkbutton4.configure(disabledforeground="#a3a3a3")
        self.Checkbutton4.configure(foreground="#000000")
        self.Checkbutton4.configure(highlightbackground="#d9d9d9")
        self.Checkbutton4.configure(highlightcolor="black")
        self.Checkbutton4.configure(justify='left')
        self.Checkbutton4.configure(text='''Check''')
        self.Checkbutton4.configure(variable=unknown_support.che96)

        self.Checkbutton5 = tk.Checkbutton(self.TNotebook4_t0)
        self.Checkbutton5.place(relx=0.157, rely=0.435, relheight=0.036
                                , relwidth=0.06)
        self.Checkbutton5.configure(activebackground="#ececec")
        self.Checkbutton5.configure(activeforeground="#000000")
        self.Checkbutton5.configure(background="#d9d9d9")
        self.Checkbutton5.configure(disabledforeground="#a3a3a3")
        self.Checkbutton5.configure(foreground="#000000")
        self.Checkbutton5.configure(highlightbackground="#d9d9d9")
        self.Checkbutton5.configure(highlightcolor="black")
        self.Checkbutton5.configure(justify='left')
        self.Checkbutton5.configure(text='''Check''')
        self.Checkbutton5.configure(variable=unknown_support.che97)

        self.Checkbutton6 = tk.Checkbutton(self.TNotebook4_t0)
        self.Checkbutton6.place(relx=0.157, rely=0.478, relheight=0.036
                                , relwidth=0.06)
        self.Checkbutton6.configure(activebackground="#ececec")
        self.Checkbutton6.configure(activeforeground="#000000")
        self.Checkbutton6.configure(background="#d9d9d9")
        self.Checkbutton6.configure(disabledforeground="#a3a3a3")
        self.Checkbutton6.configure(foreground="#000000")
        self.Checkbutton6.configure(highlightbackground="#d9d9d9")
        self.Checkbutton6.configure(highlightcolor="black")
        self.Checkbutton6.configure(justify='left')
        self.Checkbutton6.configure(text='''Check''')
        self.Checkbutton6.configure(variable=unknown_support.che99)

        self.Button18 = tk.Button(self.TNotebook4_t0)
        self.Button18.place(relx=0.265, rely=0.391, height=24, width=47)
        self.Button18.configure(activebackground="#ececec")
        self.Button18.configure(activeforeground="#000000")
        self.Button18.configure(background="#d9d9d9")
        self.Button18.configure(disabledforeground="#a3a3a3")
        self.Button18.configure(foreground="#000000")
        self.Button18.configure(highlightbackground="#d9d9d9")
        self.Button18.configure(highlightcolor="black")
        self.Button18.configure(pady="0")
        self.Button18.configure(text='''Set''')

        self.Button2 = tk.Button(self.TNotebook4_t0)
        self.Button2.place(relx=0.265, rely=0.435, height=24, width=47)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Set''')

        self.Button19 = tk.Button(self.TNotebook4_t0)
        self.Button19.place(relx=0.265, rely=0.478, height=24, width=47)
        self.Button19.configure(activebackground="#ececec")
        self.Button19.configure(activeforeground="#000000")
        self.Button19.configure(background="#d9d9d9")
        self.Button19.configure(disabledforeground="#a3a3a3")
        self.Button19.configure(foreground="#000000")
        self.Button19.configure(highlightbackground="#d9d9d9")
        self.Button19.configure(highlightcolor="black")
        self.Button19.configure(pady="0")
        self.Button19.configure(text='''Set''')

        self.Button20 = tk.Button(self.TNotebook4_t0)
        self.Button20.place(relx=0.324, rely=0.391, height=24, width=39)
        self.Button20.configure(activebackground="#ececec")
        self.Button20.configure(activeforeground="#000000")
        self.Button20.configure(background="#d9d9d9")
        self.Button20.configure(disabledforeground="#a3a3a3")
        self.Button20.configure(foreground="#000000")
        self.Button20.configure(highlightbackground="#d9d9d9")
        self.Button20.configure(highlightcolor="black")
        self.Button20.configure(pady="0")
        self.Button20.configure(text='''Reset''')

        self.Button21 = tk.Button(self.TNotebook4_t0)
        self.Button21.place(relx=0.324, rely=0.435, height=24, width=39)
        self.Button21.configure(activebackground="#ececec")
        self.Button21.configure(activeforeground="#000000")
        self.Button21.configure(background="#d9d9d9")
        self.Button21.configure(disabledforeground="#a3a3a3")
        self.Button21.configure(foreground="#000000")
        self.Button21.configure(highlightbackground="#d9d9d9")
        self.Button21.configure(highlightcolor="black")
        self.Button21.configure(pady="0")
        self.Button21.configure(text='''Reset''')

        self.Button22 = tk.Button(self.TNotebook4_t0)
        self.Button22.place(relx=0.324, rely=0.478, height=24, width=39)
        self.Button22.configure(activebackground="#ececec")
        self.Button22.configure(activeforeground="#000000")
        self.Button22.configure(background="#d9d9d9")
        self.Button22.configure(disabledforeground="#a3a3a3")
        self.Button22.configure(foreground="#000000")
        self.Button22.configure(highlightbackground="#d9d9d9")
        self.Button22.configure(highlightcolor="black")
        self.Button22.configure(pady="0")
        self.Button22.configure(text='''Reset''')

        self.Entry9 = tk.Entry(self.TNotebook4_t1)
        self.Entry9.place(relx=0.088, rely=0.029, height=20, relwidth=0.161)
        self.Entry9.configure(background="white")
        self.Entry9.configure(disabledforeground="#a3a3a3")
        self.Entry9.configure(font="TkFixedFont")
        self.Entry9.configure(foreground="#000000")
        self.Entry9.configure(insertbackground="black")

        self.Entry10 = tk.Entry(self.TNotebook4_t1)
        self.Entry10.place(relx=0.088, rely=0.072, height=20, relwidth=0.161)
        self.Entry10.configure(background="white")
        self.Entry10.configure(disabledforeground="#a3a3a3")
        self.Entry10.configure(font="TkFixedFont")
        self.Entry10.configure(foreground="#000000")
        self.Entry10.configure(insertbackground="black")

        self.Entry11 = tk.Entry(self.TNotebook4_t1)
        self.Entry11.place(relx=0.088, rely=0.116, height=20, relwidth=0.161)
        self.Entry11.configure(background="white")
        self.Entry11.configure(disabledforeground="#a3a3a3")
        self.Entry11.configure(font="TkFixedFont")
        self.Entry11.configure(foreground="#000000")
        self.Entry11.configure(insertbackground="black")

        self.Entry12 = tk.Entry(self.TNotebook4_t1)
        self.Entry12.place(relx=0.088, rely=0.159, height=20, relwidth=0.161)
        self.Entry12.configure(background="white")
        self.Entry12.configure(disabledforeground="#a3a3a3")
        self.Entry12.configure(font="TkFixedFont")
        self.Entry12.configure(foreground="#000000")
        self.Entry12.configure(insertbackground="black")

        self.Entry13 = tk.Entry(self.TNotebook4_t1)
        self.Entry13.place(relx=0.088, rely=0.203, height=20, relwidth=0.161)
        self.Entry13.configure(background="white")
        self.Entry13.configure(disabledforeground="#a3a3a3")
        self.Entry13.configure(font="TkFixedFont")
        self.Entry13.configure(foreground="#000000")
        self.Entry13.configure(insertbackground="black")

        self.Entry14 = tk.Entry(self.TNotebook4_t1)
        self.Entry14.place(relx=0.088, rely=0.246, height=20, relwidth=0.161)
        self.Entry14.configure(background="white")
        self.Entry14.configure(disabledforeground="#a3a3a3")
        self.Entry14.configure(font="TkFixedFont")
        self.Entry14.configure(foreground="#000000")
        self.Entry14.configure(insertbackground="black")

        self.Entry15 = tk.Entry(self.TNotebook4_t1)
        self.Entry15.place(relx=0.088, rely=0.29, height=20, relwidth=0.161)
        self.Entry15.configure(background="white")
        self.Entry15.configure(disabledforeground="#a3a3a3")
        self.Entry15.configure(font="TkFixedFont")
        self.Entry15.configure(foreground="#000000")
        self.Entry15.configure(insertbackground="black")

        self.Label3 = tk.Label(self.TNotebook4_t1)
        self.Label3.place(relx=0.02, rely=0.029, height=21, width=43)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Setting''')

        self.Label4 = tk.Label(self.TNotebook4_t1)
        self.Label4.place(relx=0.02, rely=0.072, height=21, width=43)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Setting''')

        self.Label5 = tk.Label(self.TNotebook4_t1)
        self.Label5.place(relx=0.02, rely=0.116, height=21, width=43)
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''Setting''')

        self.Label6 = tk.Label(self.TNotebook4_t1)
        self.Label6.place(relx=0.02, rely=0.159, height=21, width=43)
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''Setting''')

        self.Label7 = tk.Label(self.TNotebook4_t1)
        self.Label7.place(relx=0.02, rely=0.203, height=21, width=43)
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''Setting''')

        self.Label8 = tk.Label(self.TNotebook4_t1)
        self.Label8.place(relx=0.02, rely=0.246, height=21, width=43)
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''Setting''')

        self.Label9 = tk.Label(self.TNotebook4_t1)
        self.Label9.place(relx=0.02, rely=0.29, height=21, width=43)
        self.Label9.configure(background="#d9d9d9")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(text='''Setting''')

        self.Button24 = tk.Button(self.TNotebook4_t1)
        self.Button24.place(relx=0.265, rely=0.029, height=24, width=47)
        self.Button24.configure(activebackground="#ececec")
        self.Button24.configure(activeforeground="#000000")
        self.Button24.configure(background="#d9d9d9")
        self.Button24.configure(disabledforeground="#a3a3a3")
        self.Button24.configure(foreground="#000000")
        self.Button24.configure(highlightbackground="#d9d9d9")
        self.Button24.configure(highlightcolor="black")
        self.Button24.configure(pady="0")
        self.Button24.configure(text='''Set''')

        self.Button25 = tk.Button(self.TNotebook4_t1)
        self.Button25.place(relx=0.265, rely=0.072, height=24, width=47)
        self.Button25.configure(activebackground="#ececec")
        self.Button25.configure(activeforeground="#000000")
        self.Button25.configure(background="#d9d9d9")
        self.Button25.configure(disabledforeground="#a3a3a3")
        self.Button25.configure(foreground="#000000")
        self.Button25.configure(highlightbackground="#d9d9d9")
        self.Button25.configure(highlightcolor="black")
        self.Button25.configure(pady="0")
        self.Button25.configure(text='''Set''')

        self.Button26 = tk.Button(self.TNotebook4_t1)
        self.Button26.place(relx=0.265, rely=0.116, height=24, width=47)
        self.Button26.configure(activebackground="#ececec")
        self.Button26.configure(activeforeground="#000000")
        self.Button26.configure(background="#d9d9d9")
        self.Button26.configure(disabledforeground="#a3a3a3")
        self.Button26.configure(foreground="#000000")
        self.Button26.configure(highlightbackground="#d9d9d9")
        self.Button26.configure(highlightcolor="black")
        self.Button26.configure(pady="0")
        self.Button26.configure(text='''Set''')

        self.Button27 = tk.Button(self.TNotebook4_t1)
        self.Button27.place(relx=0.265, rely=0.159, height=24, width=47)
        self.Button27.configure(activebackground="#ececec")
        self.Button27.configure(activeforeground="#000000")
        self.Button27.configure(background="#d9d9d9")
        self.Button27.configure(disabledforeground="#a3a3a3")
        self.Button27.configure(foreground="#000000")
        self.Button27.configure(highlightbackground="#d9d9d9")
        self.Button27.configure(highlightcolor="black")
        self.Button27.configure(pady="0")
        self.Button27.configure(text='''Set''')

        self.Button28 = tk.Button(self.TNotebook4_t1)
        self.Button28.place(relx=0.265, rely=0.203, height=24, width=47)
        self.Button28.configure(activebackground="#ececec")
        self.Button28.configure(activeforeground="#000000")
        self.Button28.configure(background="#d9d9d9")
        self.Button28.configure(disabledforeground="#a3a3a3")
        self.Button28.configure(foreground="#000000")
        self.Button28.configure(highlightbackground="#d9d9d9")
        self.Button28.configure(highlightcolor="black")
        self.Button28.configure(pady="0")
        self.Button28.configure(text='''Set''')

        self.Button29 = tk.Button(self.TNotebook4_t1)
        self.Button29.place(relx=0.265, rely=0.246, height=24, width=47)
        self.Button29.configure(activebackground="#ececec")
        self.Button29.configure(activeforeground="#000000")
        self.Button29.configure(background="#d9d9d9")
        self.Button29.configure(disabledforeground="#a3a3a3")
        self.Button29.configure(foreground="#000000")
        self.Button29.configure(highlightbackground="#d9d9d9")
        self.Button29.configure(highlightcolor="black")
        self.Button29.configure(pady="0")
        self.Button29.configure(text='''Set''')

        self.Button30 = tk.Button(self.TNotebook4_t1)
        self.Button30.place(relx=0.265, rely=0.29, height=24, width=47)
        self.Button30.configure(activebackground="#ececec")
        self.Button30.configure(activeforeground="#000000")
        self.Button30.configure(background="#d9d9d9")
        self.Button30.configure(disabledforeground="#a3a3a3")
        self.Button30.configure(foreground="#000000")
        self.Button30.configure(highlightbackground="#d9d9d9")
        self.Button30.configure(highlightcolor="black")
        self.Button30.configure(pady="0")
        self.Button30.configure(text='''Set''')

        self.Button32 = tk.Button(self.TNotebook4_t1)
        self.Button32.place(relx=0.324, rely=0.072, height=24, width=39)
        self.Button32.configure(activebackground="#ececec")
        self.Button32.configure(activeforeground="#000000")
        self.Button32.configure(background="#d9d9d9")
        self.Button32.configure(cursor="fleur")
        self.Button32.configure(disabledforeground="#a3a3a3")
        self.Button32.configure(foreground="#000000")
        self.Button32.configure(highlightbackground="#d9d9d9")
        self.Button32.configure(highlightcolor="black")
        self.Button32.configure(pady="0")
        self.Button32.configure(text='''Reset''')

        self.Button33 = tk.Button(self.TNotebook4_t1)
        self.Button33.place(relx=0.324, rely=0.116, height=24, width=39)
        self.Button33.configure(activebackground="#ececec")
        self.Button33.configure(activeforeground="#000000")
        self.Button33.configure(background="#d9d9d9")
        self.Button33.configure(disabledforeground="#a3a3a3")
        self.Button33.configure(foreground="#000000")
        self.Button33.configure(highlightbackground="#d9d9d9")
        self.Button33.configure(highlightcolor="black")
        self.Button33.configure(pady="0")
        self.Button33.configure(text='''Reset''')

        self.Button34 = tk.Button(self.TNotebook4_t1)
        self.Button34.place(relx=0.324, rely=0.159, height=24, width=39)
        self.Button34.configure(activebackground="#ececec")
        self.Button34.configure(activeforeground="#000000")
        self.Button34.configure(background="#d9d9d9")
        self.Button34.configure(disabledforeground="#a3a3a3")
        self.Button34.configure(foreground="#000000")
        self.Button34.configure(highlightbackground="#d9d9d9")
        self.Button34.configure(highlightcolor="black")
        self.Button34.configure(pady="0")
        self.Button34.configure(text='''Reset''')

        self.Button35 = tk.Button(self.TNotebook4_t1)
        self.Button35.place(relx=0.324, rely=0.203, height=24, width=39)
        self.Button35.configure(activebackground="#ececec")
        self.Button35.configure(activeforeground="#000000")
        self.Button35.configure(background="#d9d9d9")
        self.Button35.configure(disabledforeground="#a3a3a3")
        self.Button35.configure(foreground="#000000")
        self.Button35.configure(highlightbackground="#d9d9d9")
        self.Button35.configure(highlightcolor="black")
        self.Button35.configure(pady="0")
        self.Button35.configure(text='''Reset''')

        self.Button36 = tk.Button(self.TNotebook4_t1)
        self.Button36.place(relx=0.324, rely=0.246, height=24, width=39)
        self.Button36.configure(activebackground="#ececec")
        self.Button36.configure(activeforeground="#000000")
        self.Button36.configure(background="#d9d9d9")
        self.Button36.configure(disabledforeground="#a3a3a3")
        self.Button36.configure(foreground="#000000")
        self.Button36.configure(highlightbackground="#d9d9d9")
        self.Button36.configure(highlightcolor="black")
        self.Button36.configure(pady="0")
        self.Button36.configure(text='''Reset''')

        self.Button37 = tk.Button(self.TNotebook4_t1)
        self.Button37.place(relx=0.324, rely=0.29, height=24, width=39)
        self.Button37.configure(activebackground="#ececec")
        self.Button37.configure(activeforeground="#000000")
        self.Button37.configure(background="#d9d9d9")
        self.Button37.configure(disabledforeground="#a3a3a3")
        self.Button37.configure(foreground="#000000")
        self.Button37.configure(highlightbackground="#d9d9d9")
        self.Button37.configure(highlightcolor="black")
        self.Button37.configure(pady="0")
        self.Button37.configure(text='''Reset''')

        self.Button31 = tk.Button(self.TNotebook4_t1)
        self.Button31.place(relx=0.324, rely=0.029, height=24, width=39)
        self.Button31.configure(activebackground="#ececec")
        self.Button31.configure(activeforeground="#000000")
        self.Button31.configure(background="#d9d9d9")
        self.Button31.configure(disabledforeground="#a3a3a3")
        self.Button31.configure(foreground="#000000")
        self.Button31.configure(highlightbackground="#d9d9d9")
        self.Button31.configure(highlightcolor="black")
        self.Button31.configure(pady="0")
        self.Button31.configure(text='''Reset''')

        self.Checkbutton7 = tk.Checkbutton(self.TNotebook4_t1)
        self.Checkbutton7.place(relx=0.088, rely=0.391, relheight=0.036
                                , relwidth=0.06)
        self.Checkbutton7.configure(activebackground="#ececec")
        self.Checkbutton7.configure(activeforeground="#000000")
        self.Checkbutton7.configure(background="#d9d9d9")
        self.Checkbutton7.configure(disabledforeground="#a3a3a3")
        self.Checkbutton7.configure(foreground="#000000")
        self.Checkbutton7.configure(highlightbackground="#d9d9d9")
        self.Checkbutton7.configure(highlightcolor="black")
        self.Checkbutton7.configure(justify='left')
        self.Checkbutton7.configure(text='''Check''')
        self.Checkbutton7.configure(variable=unknown_support.che72)

        self.Checkbutton8 = tk.Checkbutton(self.TNotebook4_t1)
        self.Checkbutton8.place(relx=0.088, rely=0.435, relheight=0.036
                                , relwidth=0.06)
        self.Checkbutton8.configure(activebackground="#ececec")
        self.Checkbutton8.configure(activeforeground="#000000")
        self.Checkbutton8.configure(background="#d9d9d9")
        self.Checkbutton8.configure(disabledforeground="#a3a3a3")
        self.Checkbutton8.configure(foreground="#000000")
        self.Checkbutton8.configure(highlightbackground="#d9d9d9")
        self.Checkbutton8.configure(highlightcolor="black")
        self.Checkbutton8.configure(justify='left')
        self.Checkbutton8.configure(text='''Check''')
        self.Checkbutton8.configure(variable=unknown_support.che73)

        self.Checkbutton9 = tk.Checkbutton(self.TNotebook4_t1)
        self.Checkbutton9.place(relx=0.088, rely=0.478, relheight=0.036
                                , relwidth=0.06)
        self.Checkbutton9.configure(activebackground="#ececec")
        self.Checkbutton9.configure(activeforeground="#000000")
        self.Checkbutton9.configure(background="#d9d9d9")
        self.Checkbutton9.configure(disabledforeground="#a3a3a3")
        self.Checkbutton9.configure(foreground="#000000")
        self.Checkbutton9.configure(highlightbackground="#d9d9d9")
        self.Checkbutton9.configure(highlightcolor="black")
        self.Checkbutton9.configure(justify='left')
        self.Checkbutton9.configure(text='''Check''')
        self.Checkbutton9.configure(variable=unknown_support.che74)

        self.Checkbutton10 = tk.Checkbutton(self.TNotebook4_t1)
        self.Checkbutton10.place(relx=0.157, rely=0.391, relheight=0.036
                                 , relwidth=0.06)
        self.Checkbutton10.configure(activebackground="#ececec")
        self.Checkbutton10.configure(activeforeground="#000000")
        self.Checkbutton10.configure(background="#d9d9d9")
        self.Checkbutton10.configure(disabledforeground="#a3a3a3")
        self.Checkbutton10.configure(foreground="#000000")
        self.Checkbutton10.configure(highlightbackground="#d9d9d9")
        self.Checkbutton10.configure(highlightcolor="black")
        self.Checkbutton10.configure(justify='left')
        self.Checkbutton10.configure(text='''Check''')
        self.Checkbutton10.configure(variable=unknown_support.che75)

        self.Checkbutton11 = tk.Checkbutton(self.TNotebook4_t1)
        self.Checkbutton11.place(relx=0.157, rely=0.435, relheight=0.036
                                 , relwidth=0.06)
        self.Checkbutton11.configure(activebackground="#ececec")
        self.Checkbutton11.configure(activeforeground="#000000")
        self.Checkbutton11.configure(background="#d9d9d9")
        self.Checkbutton11.configure(disabledforeground="#a3a3a3")
        self.Checkbutton11.configure(foreground="#000000")
        self.Checkbutton11.configure(highlightbackground="#d9d9d9")
        self.Checkbutton11.configure(highlightcolor="black")
        self.Checkbutton11.configure(justify='left')
        self.Checkbutton11.configure(text='''Check''')
        self.Checkbutton11.configure(variable=unknown_support.che76)

        self.Checkbutton12 = tk.Checkbutton(self.TNotebook4_t1)
        self.Checkbutton12.place(relx=0.157, rely=0.478, relheight=0.036
                                 , relwidth=0.06)
        self.Checkbutton12.configure(activebackground="#ececec")
        self.Checkbutton12.configure(activeforeground="#000000")
        self.Checkbutton12.configure(background="#d9d9d9")
        self.Checkbutton12.configure(disabledforeground="#a3a3a3")
        self.Checkbutton12.configure(foreground="#000000")
        self.Checkbutton12.configure(highlightbackground="#d9d9d9")
        self.Checkbutton12.configure(highlightcolor="black")
        self.Checkbutton12.configure(justify='left')
        self.Checkbutton12.configure(text='''Check''')
        self.Checkbutton12.configure(variable=unknown_support.che77)

        self.Button38 = tk.Button(self.TNotebook4_t1)
        self.Button38.place(relx=0.265, rely=0.333, height=24, width=47)
        self.Button38.configure(activebackground="#ececec")
        self.Button38.configure(activeforeground="#000000")
        self.Button38.configure(background="#d9d9d9")
        self.Button38.configure(disabledforeground="#a3a3a3")
        self.Button38.configure(foreground="#000000")
        self.Button38.configure(highlightbackground="#d9d9d9")
        self.Button38.configure(highlightcolor="black")
        self.Button38.configure(pady="0")
        self.Button38.configure(text='''Set''')

        self.Button39 = tk.Button(self.TNotebook4_t1)
        self.Button39.place(relx=0.265, rely=0.391, height=24, width=47)
        self.Button39.configure(activebackground="#ececec")
        self.Button39.configure(activeforeground="#000000")
        self.Button39.configure(background="#d9d9d9")
        self.Button39.configure(disabledforeground="#a3a3a3")
        self.Button39.configure(foreground="#000000")
        self.Button39.configure(highlightbackground="#d9d9d9")
        self.Button39.configure(highlightcolor="black")
        self.Button39.configure(pady="0")
        self.Button39.configure(text='''Set''')

        self.Button40 = tk.Button(self.TNotebook4_t1)
        self.Button40.place(relx=0.265, rely=0.435, height=24, width=47)
        self.Button40.configure(activebackground="#ececec")
        self.Button40.configure(activeforeground="#000000")
        self.Button40.configure(background="#d9d9d9")
        self.Button40.configure(disabledforeground="#a3a3a3")
        self.Button40.configure(foreground="#000000")
        self.Button40.configure(highlightbackground="#d9d9d9")
        self.Button40.configure(highlightcolor="black")
        self.Button40.configure(pady="0")
        self.Button40.configure(text='''Set''')

        self.Button41 = tk.Button(self.TNotebook4_t1)
        self.Button41.place(relx=0.324, rely=0.333, height=24, width=39)
        self.Button41.configure(activebackground="#ececec")
        self.Button41.configure(activeforeground="#000000")
        self.Button41.configure(background="#d9d9d9")
        self.Button41.configure(disabledforeground="#a3a3a3")
        self.Button41.configure(foreground="#000000")
        self.Button41.configure(highlightbackground="#d9d9d9")
        self.Button41.configure(highlightcolor="black")
        self.Button41.configure(pady="0")
        self.Button41.configure(text='''Reset''')

        self.Button42 = tk.Button(self.TNotebook4_t1)
        self.Button42.place(relx=0.324, rely=0.391, height=24, width=39)
        self.Button42.configure(activebackground="#ececec")
        self.Button42.configure(activeforeground="#000000")
        self.Button42.configure(background="#d9d9d9")
        self.Button42.configure(disabledforeground="#a3a3a3")
        self.Button42.configure(foreground="#000000")
        self.Button42.configure(highlightbackground="#d9d9d9")
        self.Button42.configure(highlightcolor="black")
        self.Button42.configure(pady="0")
        self.Button42.configure(text='''Reset''')

        self.Button43 = tk.Button(self.TNotebook4_t1)
        self.Button43.place(relx=0.324, rely=0.435, height=24, width=39)
        self.Button43.configure(activebackground="#ececec")
        self.Button43.configure(activeforeground="#000000")
        self.Button43.configure(background="#d9d9d9")
        self.Button43.configure(disabledforeground="#a3a3a3")
        self.Button43.configure(foreground="#000000")
        self.Button43.configure(highlightbackground="#d9d9d9")
        self.Button43.configure(highlightcolor="black")
        self.Button43.configure(pady="0")
        self.Button43.configure(text='''Reset''')

        self.Entry24 = tk.Entry(self.TNotebook4_t1)
        self.Entry24.place(relx=0.088, rely=0.333, height=20, relwidth=0.161)
        self.Entry24.configure(background="white")
        self.Entry24.configure(disabledforeground="#a3a3a3")
        self.Entry24.configure(font="TkFixedFont")
        self.Entry24.configure(foreground="#000000")
        self.Entry24.configure(insertbackground="black")

        self.Button66 = tk.Button(self.TNotebook4_t1)
        self.Button66.place(relx=0.265, rely=0.478, height=24, width=47)
        self.Button66.configure(activebackground="#ececec")
        self.Button66.configure(activeforeground="#000000")
        self.Button66.configure(background="#d9d9d9")
        self.Button66.configure(disabledforeground="#a3a3a3")
        self.Button66.configure(foreground="#000000")
        self.Button66.configure(highlightbackground="#d9d9d9")
        self.Button66.configure(highlightcolor="black")
        self.Button66.configure(pady="0")
        self.Button66.configure(text='''Set''')

        self.Button67 = tk.Button(self.TNotebook4_t1)
        self.Button67.place(relx=0.324, rely=0.478, height=24, width=39)
        self.Button67.configure(activebackground="#ececec")
        self.Button67.configure(activeforeground="#000000")
        self.Button67.configure(background="#d9d9d9")
        self.Button67.configure(disabledforeground="#a3a3a3")
        self.Button67.configure(foreground="#000000")
        self.Button67.configure(highlightbackground="#d9d9d9")
        self.Button67.configure(highlightcolor="black")
        self.Button67.configure(pady="0")
        self.Button67.configure(text='''Reset''')

        self.Label18 = tk.Label(self.TNotebook4_t1)
        self.Label18.place(relx=0.02, rely=0.333, height=21, width=43)
        self.Label18.configure(background="#d9d9d9")
        self.Label18.configure(disabledforeground="#a3a3a3")
        self.Label18.configure(foreground="#000000")
        self.Label18.configure(text='''Setting''')

        self.Entry16 = tk.Entry(self.TNotebook4_t2)
        self.Entry16.place(relx=0.088, rely=0.029, height=20, relwidth=0.161)
        self.Entry16.configure(background="white")
        self.Entry16.configure(disabledforeground="#a3a3a3")
        self.Entry16.configure(font="TkFixedFont")
        self.Entry16.configure(foreground="#000000")
        self.Entry16.configure(insertbackground="black")

        self.Entry17 = tk.Entry(self.TNotebook4_t2)
        self.Entry17.place(relx=0.088, rely=0.072, height=20, relwidth=0.161)
        self.Entry17.configure(background="white")
        self.Entry17.configure(disabledforeground="#a3a3a3")
        self.Entry17.configure(font="TkFixedFont")
        self.Entry17.configure(foreground="#000000")
        self.Entry17.configure(insertbackground="black")

        self.Entry18 = tk.Entry(self.TNotebook4_t2)
        self.Entry18.place(relx=0.088, rely=0.116, height=20, relwidth=0.161)
        self.Entry18.configure(background="white")
        self.Entry18.configure(disabledforeground="#a3a3a3")
        self.Entry18.configure(font="TkFixedFont")
        self.Entry18.configure(foreground="#000000")
        self.Entry18.configure(insertbackground="black")

        self.Entry19 = tk.Entry(self.TNotebook4_t2)
        self.Entry19.place(relx=0.088, rely=0.159, height=20, relwidth=0.161)
        self.Entry19.configure(background="white")
        self.Entry19.configure(disabledforeground="#a3a3a3")
        self.Entry19.configure(font="TkFixedFont")
        self.Entry19.configure(foreground="#000000")
        self.Entry19.configure(insertbackground="black")

        self.Entry20 = tk.Entry(self.TNotebook4_t2)
        self.Entry20.place(relx=0.088, rely=0.203, height=20, relwidth=0.161)
        self.Entry20.configure(background="white")
        self.Entry20.configure(disabledforeground="#a3a3a3")
        self.Entry20.configure(font="TkFixedFont")
        self.Entry20.configure(foreground="#000000")
        self.Entry20.configure(insertbackground="black")

        self.Entry21 = tk.Entry(self.TNotebook4_t2)
        self.Entry21.place(relx=0.088, rely=0.246, height=20, relwidth=0.161)
        self.Entry21.configure(background="white")
        self.Entry21.configure(disabledforeground="#a3a3a3")
        self.Entry21.configure(font="TkFixedFont")
        self.Entry21.configure(foreground="#000000")
        self.Entry21.configure(insertbackground="black")

        self.Entry22 = tk.Entry(self.TNotebook4_t2)
        self.Entry22.place(relx=0.088, rely=0.29, height=20, relwidth=0.161)
        self.Entry22.configure(background="white")
        self.Entry22.configure(disabledforeground="#a3a3a3")
        self.Entry22.configure(font="TkFixedFont")
        self.Entry22.configure(foreground="#000000")
        self.Entry22.configure(insertbackground="black")

        self.Entry23 = tk.Entry(self.TNotebook4_t2)
        self.Entry23.place(relx=0.088, rely=0.333, height=20, relwidth=0.161)
        self.Entry23.configure(background="white")
        self.Entry23.configure(disabledforeground="#a3a3a3")
        self.Entry23.configure(font="TkFixedFont")
        self.Entry23.configure(foreground="#000000")
        self.Entry23.configure(insertbackground="black")

        self.Label10 = tk.Label(self.TNotebook4_t2)
        self.Label10.place(relx=0.02, rely=0.029, height=21, width=43)
        self.Label10.configure(background="#d9d9d9")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(text='''Setting''')

        self.Label11 = tk.Label(self.TNotebook4_t2)
        self.Label11.place(relx=0.02, rely=0.072, height=21, width=44)
        self.Label11.configure(background="#d9d9d9")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(text='''Setting''')

        self.Label12 = tk.Label(self.TNotebook4_t2)
        self.Label12.place(relx=0.02, rely=0.116, height=21, width=43)
        self.Label12.configure(background="#d9d9d9")
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(foreground="#000000")
        self.Label12.configure(text='''Setting''')

        self.Label13 = tk.Label(self.TNotebook4_t2)
        self.Label13.place(relx=0.02, rely=0.159, height=21, width=43)
        self.Label13.configure(background="#d9d9d9")
        self.Label13.configure(disabledforeground="#a3a3a3")
        self.Label13.configure(foreground="#000000")
        self.Label13.configure(text='''Setting''')

        self.Label14 = tk.Label(self.TNotebook4_t2)
        self.Label14.place(relx=0.02, rely=0.203, height=21, width=43)
        self.Label14.configure(background="#d9d9d9")
        self.Label14.configure(disabledforeground="#a3a3a3")
        self.Label14.configure(foreground="#000000")
        self.Label14.configure(text='''Setting''')

        self.Label15 = tk.Label(self.TNotebook4_t2)
        self.Label15.place(relx=0.02, rely=0.246, height=21, width=43)
        self.Label15.configure(background="#d9d9d9")
        self.Label15.configure(disabledforeground="#a3a3a3")
        self.Label15.configure(foreground="#000000")
        self.Label15.configure(text='''Setting''')

        self.Label16 = tk.Label(self.TNotebook4_t2)
        self.Label16.place(relx=0.02, rely=0.29, height=21, width=43)
        self.Label16.configure(background="#d9d9d9")
        self.Label16.configure(disabledforeground="#a3a3a3")
        self.Label16.configure(foreground="#000000")
        self.Label16.configure(text='''Setting''')

        self.Label17 = tk.Label(self.TNotebook4_t2)
        self.Label17.place(relx=0.02, rely=0.333, height=21, width=43)
        self.Label17.configure(background="#d9d9d9")
        self.Label17.configure(disabledforeground="#a3a3a3")
        self.Label17.configure(foreground="#000000")
        self.Label17.configure(text='''Setting''')

        self.Button44 = tk.Button(self.TNotebook4_t2)
        self.Button44.place(relx=0.265, rely=0.029, height=24, width=47)
        self.Button44.configure(activebackground="#ececec")
        self.Button44.configure(activeforeground="#000000")
        self.Button44.configure(background="#d9d9d9")
        self.Button44.configure(disabledforeground="#a3a3a3")
        self.Button44.configure(foreground="#000000")
        self.Button44.configure(highlightbackground="#d9d9d9")
        self.Button44.configure(highlightcolor="black")
        self.Button44.configure(pady="0")
        self.Button44.configure(text='''Set''')

        self.Button45 = tk.Button(self.TNotebook4_t2)
        self.Button45.place(relx=0.265, rely=0.072, height=24, width=47)
        self.Button45.configure(activebackground="#ececec")
        self.Button45.configure(activeforeground="#000000")
        self.Button45.configure(background="#d9d9d9")
        self.Button45.configure(disabledforeground="#a3a3a3")
        self.Button45.configure(foreground="#000000")
        self.Button45.configure(highlightbackground="#d9d9d9")
        self.Button45.configure(highlightcolor="black")
        self.Button45.configure(pady="0")
        self.Button45.configure(text='''Set''')

        self.Button46 = tk.Button(self.TNotebook4_t2)
        self.Button46.place(relx=0.265, rely=0.116, height=24, width=47)
        self.Button46.configure(activebackground="#ececec")
        self.Button46.configure(activeforeground="#000000")
        self.Button46.configure(background="#d9d9d9")
        self.Button46.configure(disabledforeground="#a3a3a3")
        self.Button46.configure(foreground="#000000")
        self.Button46.configure(highlightbackground="#d9d9d9")
        self.Button46.configure(highlightcolor="black")
        self.Button46.configure(pady="0")
        self.Button46.configure(text='''Set''')

        self.Button47 = tk.Button(self.TNotebook4_t2)
        self.Button47.place(relx=0.265, rely=0.159, height=24, width=47)
        self.Button47.configure(activebackground="#ececec")
        self.Button47.configure(activeforeground="#000000")
        self.Button47.configure(background="#d9d9d9")
        self.Button47.configure(disabledforeground="#a3a3a3")
        self.Button47.configure(foreground="#000000")
        self.Button47.configure(highlightbackground="#d9d9d9")
        self.Button47.configure(highlightcolor="black")
        self.Button47.configure(pady="0")
        self.Button47.configure(text='''Set''')

        self.Button48 = tk.Button(self.TNotebook4_t2)
        self.Button48.place(relx=0.265, rely=0.203, height=24, width=47)
        self.Button48.configure(activebackground="#ececec")
        self.Button48.configure(activeforeground="#000000")
        self.Button48.configure(background="#d9d9d9")
        self.Button48.configure(cursor="fleur")
        self.Button48.configure(disabledforeground="#a3a3a3")
        self.Button48.configure(foreground="#000000")
        self.Button48.configure(highlightbackground="#d9d9d9")
        self.Button48.configure(highlightcolor="black")
        self.Button48.configure(pady="0")
        self.Button48.configure(text='''Set''')

        self.Button49 = tk.Button(self.TNotebook4_t2)
        self.Button49.place(relx=0.265, rely=0.246, height=24, width=47)
        self.Button49.configure(activebackground="#ececec")
        self.Button49.configure(activeforeground="#000000")
        self.Button49.configure(background="#d9d9d9")
        self.Button49.configure(disabledforeground="#a3a3a3")
        self.Button49.configure(foreground="#000000")
        self.Button49.configure(highlightbackground="#d9d9d9")
        self.Button49.configure(highlightcolor="black")
        self.Button49.configure(pady="0")
        self.Button49.configure(text='''Set''')

        self.Button50 = tk.Button(self.TNotebook4_t2)
        self.Button50.place(relx=0.265, rely=0.29, height=24, width=47)
        self.Button50.configure(activebackground="#ececec")
        self.Button50.configure(activeforeground="#000000")
        self.Button50.configure(background="#d9d9d9")
        self.Button50.configure(cursor="fleur")
        self.Button50.configure(disabledforeground="#a3a3a3")
        self.Button50.configure(foreground="#000000")
        self.Button50.configure(highlightbackground="#d9d9d9")
        self.Button50.configure(highlightcolor="black")
        self.Button50.configure(pady="0")
        self.Button50.configure(text='''Set''')

        self.Button51 = tk.Button(self.TNotebook4_t2)
        self.Button51.place(relx=0.265, rely=0.333, height=24, width=47)
        self.Button51.configure(activebackground="#ececec")
        self.Button51.configure(activeforeground="#000000")
        self.Button51.configure(background="#d9d9d9")
        self.Button51.configure(cursor="fleur")
        self.Button51.configure(disabledforeground="#a3a3a3")
        self.Button51.configure(foreground="#000000")
        self.Button51.configure(highlightbackground="#d9d9d9")
        self.Button51.configure(highlightcolor="black")
        self.Button51.configure(pady="0")
        self.Button51.configure(text='''Set''')

        self.Button52 = tk.Button(self.TNotebook4_t2)
        self.Button52.place(relx=0.324, rely=0.029, height=24, width=39)
        self.Button52.configure(activebackground="#ececec")
        self.Button52.configure(activeforeground="#000000")
        self.Button52.configure(background="#d9d9d9")
        self.Button52.configure(disabledforeground="#a3a3a3")
        self.Button52.configure(foreground="#000000")
        self.Button52.configure(highlightbackground="#d9d9d9")
        self.Button52.configure(highlightcolor="black")
        self.Button52.configure(pady="0")
        self.Button52.configure(text='''Reset''')

        self.Button53 = tk.Button(self.TNotebook4_t2)
        self.Button53.place(relx=0.324, rely=0.072, height=24, width=39)
        self.Button53.configure(activebackground="#ececec")
        self.Button53.configure(activeforeground="#000000")
        self.Button53.configure(background="#d9d9d9")
        self.Button53.configure(disabledforeground="#a3a3a3")
        self.Button53.configure(foreground="#000000")
        self.Button53.configure(highlightbackground="#d9d9d9")
        self.Button53.configure(highlightcolor="black")
        self.Button53.configure(pady="0")
        self.Button53.configure(text='''Reset''')

        self.Button54 = tk.Button(self.TNotebook4_t2)
        self.Button54.place(relx=0.324, rely=0.116, height=24, width=39)
        self.Button54.configure(activebackground="#ececec")
        self.Button54.configure(activeforeground="#000000")
        self.Button54.configure(background="#d9d9d9")
        self.Button54.configure(disabledforeground="#a3a3a3")
        self.Button54.configure(foreground="#000000")
        self.Button54.configure(highlightbackground="#d9d9d9")
        self.Button54.configure(highlightcolor="black")
        self.Button54.configure(pady="0")
        self.Button54.configure(text='''Reset''')

        self.Button55 = tk.Button(self.TNotebook4_t2)
        self.Button55.place(relx=0.324, rely=0.159, height=24, width=39)
        self.Button55.configure(activebackground="#ececec")
        self.Button55.configure(activeforeground="#000000")
        self.Button55.configure(background="#d9d9d9")
        self.Button55.configure(disabledforeground="#a3a3a3")
        self.Button55.configure(foreground="#000000")
        self.Button55.configure(highlightbackground="#d9d9d9")
        self.Button55.configure(highlightcolor="black")
        self.Button55.configure(pady="0")
        self.Button55.configure(text='''Reset''')

        self.Button56 = tk.Button(self.TNotebook4_t2)
        self.Button56.place(relx=0.324, rely=0.203, height=24, width=39)
        self.Button56.configure(activebackground="#ececec")
        self.Button56.configure(activeforeground="#000000")
        self.Button56.configure(background="#d9d9d9")
        self.Button56.configure(disabledforeground="#a3a3a3")
        self.Button56.configure(foreground="#000000")
        self.Button56.configure(highlightbackground="#d9d9d9")
        self.Button56.configure(highlightcolor="black")
        self.Button56.configure(pady="0")
        self.Button56.configure(text='''Reset''')

        self.Button57 = tk.Button(self.TNotebook4_t2)
        self.Button57.place(relx=0.324, rely=0.246, height=24, width=39)
        self.Button57.configure(activebackground="#ececec")
        self.Button57.configure(activeforeground="#000000")
        self.Button57.configure(background="#d9d9d9")
        self.Button57.configure(disabledforeground="#a3a3a3")
        self.Button57.configure(foreground="#000000")
        self.Button57.configure(highlightbackground="#d9d9d9")
        self.Button57.configure(highlightcolor="black")
        self.Button57.configure(pady="0")
        self.Button57.configure(text='''Reset''')

        self.Button58 = tk.Button(self.TNotebook4_t2)
        self.Button58.place(relx=0.324, rely=0.29, height=24, width=39)
        self.Button58.configure(activebackground="#ececec")
        self.Button58.configure(activeforeground="#000000")
        self.Button58.configure(background="#d9d9d9")
        self.Button58.configure(disabledforeground="#a3a3a3")
        self.Button58.configure(foreground="#000000")
        self.Button58.configure(highlightbackground="#d9d9d9")
        self.Button58.configure(highlightcolor="black")
        self.Button58.configure(pady="0")
        self.Button58.configure(text='''Reset''')

        self.Button59 = tk.Button(self.TNotebook4_t2)
        self.Button59.place(relx=0.324, rely=0.333, height=24, width=39)
        self.Button59.configure(activebackground="#ececec")
        self.Button59.configure(activeforeground="#000000")
        self.Button59.configure(background="#d9d9d9")
        self.Button59.configure(disabledforeground="#a3a3a3")
        self.Button59.configure(foreground="#000000")
        self.Button59.configure(highlightbackground="#d9d9d9")
        self.Button59.configure(highlightcolor="black")
        self.Button59.configure(pady="0")
        self.Button59.configure(text='''Reset''')

        self.Checkbutton13 = tk.Checkbutton(self.TNotebook4_t2)
        self.Checkbutton13.place(relx=0.088, rely=0.391, relheight=0.036
                                 , relwidth=0.06)
        self.Checkbutton13.configure(activebackground="#ececec")
        self.Checkbutton13.configure(activeforeground="#000000")
        self.Checkbutton13.configure(background="#d9d9d9")
        self.Checkbutton13.configure(disabledforeground="#a3a3a3")
        self.Checkbutton13.configure(foreground="#000000")
        self.Checkbutton13.configure(highlightbackground="#d9d9d9")
        self.Checkbutton13.configure(highlightcolor="black")
        self.Checkbutton13.configure(justify='left')
        self.Checkbutton13.configure(text='''Check''')
        self.Checkbutton13.configure(variable=unknown_support.che120)

        self.Checkbutton14 = tk.Checkbutton(self.TNotebook4_t2)
        self.Checkbutton14.place(relx=0.088, rely=0.435, relheight=0.036
                                 , relwidth=0.06)
        self.Checkbutton14.configure(activebackground="#ececec")
        self.Checkbutton14.configure(activeforeground="#000000")
        self.Checkbutton14.configure(background="#d9d9d9")
        self.Checkbutton14.configure(disabledforeground="#a3a3a3")
        self.Checkbutton14.configure(foreground="#000000")
        self.Checkbutton14.configure(highlightbackground="#d9d9d9")
        self.Checkbutton14.configure(highlightcolor="black")
        self.Checkbutton14.configure(justify='left')
        self.Checkbutton14.configure(text='''Check''')
        self.Checkbutton14.configure(variable=unknown_support.che121)

        self.Checkbutton15 = tk.Checkbutton(self.TNotebook4_t2)
        self.Checkbutton15.place(relx=0.088, rely=0.478, relheight=0.036
                                 , relwidth=0.06)
        self.Checkbutton15.configure(activebackground="#ececec")
        self.Checkbutton15.configure(activeforeground="#000000")
        self.Checkbutton15.configure(background="#d9d9d9")
        self.Checkbutton15.configure(disabledforeground="#a3a3a3")
        self.Checkbutton15.configure(foreground="#000000")
        self.Checkbutton15.configure(highlightbackground="#d9d9d9")
        self.Checkbutton15.configure(highlightcolor="black")
        self.Checkbutton15.configure(justify='left')
        self.Checkbutton15.configure(text='''Check''')
        self.Checkbutton15.configure(variable=unknown_support.che122)

        self.Checkbutton16 = tk.Checkbutton(self.TNotebook4_t2)
        self.Checkbutton16.place(relx=0.157, rely=0.391, relheight=0.036
                                 , relwidth=0.06)
        self.Checkbutton16.configure(activebackground="#ececec")
        self.Checkbutton16.configure(activeforeground="#000000")
        self.Checkbutton16.configure(background="#d9d9d9")
        self.Checkbutton16.configure(disabledforeground="#a3a3a3")
        self.Checkbutton16.configure(foreground="#000000")
        self.Checkbutton16.configure(highlightbackground="#d9d9d9")
        self.Checkbutton16.configure(highlightcolor="black")
        self.Checkbutton16.configure(justify='left')
        self.Checkbutton16.configure(text='''Check''')
        self.Checkbutton16.configure(variable=unknown_support.che123)

        self.Checkbutton17 = tk.Checkbutton(self.TNotebook4_t2)
        self.Checkbutton17.place(relx=0.157, rely=0.435, relheight=0.036
                                 , relwidth=0.06)
        self.Checkbutton17.configure(activebackground="#ececec")
        self.Checkbutton17.configure(activeforeground="#000000")
        self.Checkbutton17.configure(background="#d9d9d9")
        self.Checkbutton17.configure(disabledforeground="#a3a3a3")
        self.Checkbutton17.configure(foreground="#000000")
        self.Checkbutton17.configure(highlightbackground="#d9d9d9")
        self.Checkbutton17.configure(highlightcolor="black")
        self.Checkbutton17.configure(justify='left')
        self.Checkbutton17.configure(text='''Check''')
        self.Checkbutton17.configure(variable=unknown_support.che124)

        self.Checkbutton18 = tk.Checkbutton(self.TNotebook4_t2)
        self.Checkbutton18.place(relx=0.157, rely=0.478, relheight=0.036
                                 , relwidth=0.06)
        self.Checkbutton18.configure(activebackground="#ececec")
        self.Checkbutton18.configure(activeforeground="#000000")
        self.Checkbutton18.configure(background="#d9d9d9")
        self.Checkbutton18.configure(disabledforeground="#a3a3a3")
        self.Checkbutton18.configure(foreground="#000000")
        self.Checkbutton18.configure(highlightbackground="#d9d9d9")
        self.Checkbutton18.configure(highlightcolor="black")
        self.Checkbutton18.configure(justify='left')
        self.Checkbutton18.configure(text='''Check''')
        self.Checkbutton18.configure(variable=unknown_support.che125)

        self.Button60 = tk.Button(self.TNotebook4_t2)
        self.Button60.place(relx=0.265, rely=0.391, height=24, width=47)
        self.Button60.configure(activebackground="#ececec")
        self.Button60.configure(activeforeground="#000000")
        self.Button60.configure(background="#d9d9d9")
        self.Button60.configure(disabledforeground="#a3a3a3")
        self.Button60.configure(foreground="#000000")
        self.Button60.configure(highlightbackground="#d9d9d9")
        self.Button60.configure(highlightcolor="black")
        self.Button60.configure(pady="0")
        self.Button60.configure(text='''Set''')

        self.Button61 = tk.Button(self.TNotebook4_t2)
        self.Button61.place(relx=0.265, rely=0.435, height=24, width=47)
        self.Button61.configure(activebackground="#ececec")
        self.Button61.configure(activeforeground="#000000")
        self.Button61.configure(background="#d9d9d9")
        self.Button61.configure(disabledforeground="#a3a3a3")
        self.Button61.configure(foreground="#000000")
        self.Button61.configure(highlightbackground="#d9d9d9")
        self.Button61.configure(highlightcolor="black")
        self.Button61.configure(pady="0")
        self.Button61.configure(text='''Set''')

        self.Button62 = tk.Button(self.TNotebook4_t2)
        self.Button62.place(relx=0.265, rely=0.478, height=24, width=47)
        self.Button62.configure(activebackground="#ececec")
        self.Button62.configure(activeforeground="#000000")
        self.Button62.configure(background="#d9d9d9")
        self.Button62.configure(disabledforeground="#a3a3a3")
        self.Button62.configure(foreground="#000000")
        self.Button62.configure(highlightbackground="#d9d9d9")
        self.Button62.configure(highlightcolor="black")
        self.Button62.configure(pady="0")
        self.Button62.configure(text='''Set''')

        self.Button63 = tk.Button(self.TNotebook4_t2)
        self.Button63.place(relx=0.324, rely=0.391, height=24, width=39)
        self.Button63.configure(activebackground="#ececec")
        self.Button63.configure(activeforeground="#000000")
        self.Button63.configure(background="#d9d9d9")
        self.Button63.configure(disabledforeground="#a3a3a3")
        self.Button63.configure(foreground="#000000")
        self.Button63.configure(highlightbackground="#d9d9d9")
        self.Button63.configure(highlightcolor="black")
        self.Button63.configure(pady="0")
        self.Button63.configure(text='''Reset''')

        self.Button64 = tk.Button(self.TNotebook4_t2)
        self.Button64.place(relx=0.324, rely=0.435, height=24, width=39)
        self.Button64.configure(activebackground="#ececec")
        self.Button64.configure(activeforeground="#000000")
        self.Button64.configure(background="#d9d9d9")
        self.Button64.configure(disabledforeground="#a3a3a3")
        self.Button64.configure(foreground="#000000")
        self.Button64.configure(highlightbackground="#d9d9d9")
        self.Button64.configure(highlightcolor="black")
        self.Button64.configure(pady="0")
        self.Button64.configure(text='''Reset''')

        self.Button65 = tk.Button(self.TNotebook4_t2)
        self.Button65.place(relx=0.324, rely=0.478, height=24, width=39)
        self.Button65.configure(activebackground="#ececec")
        self.Button65.configure(activeforeground="#000000")
        self.Button65.configure(background="#d9d9d9")
        self.Button65.configure(disabledforeground="#a3a3a3")
        self.Button65.configure(foreground="#000000")
        self.Button65.configure(highlightbackground="#d9d9d9")
        self.Button65.configure(highlightcolor="black")
        self.Button65.configure(pady="0")
        self.Button65.configure(text='''Reset''')

        self.Label1 = tk.Label(self.TNotebook1_t3)
        self.Label1.place(relx=0.01, rely=0.014, height=391, width=674)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Cuckservative
From Wikipedia, the free encyclopedia
Jump to navigationJump to search
"Cuckservative" is a pejorative[1] formed as a portmanteau of "cuck", a shortened form of the word cuckold, and the political designation conservative.[2] It has become a label used by white nationalists and the alt-right in the United States.[3][4][5][6]

The word "cuckservative" reached a high level of mainstream political conversation around mid-July 2015, where it gained media attention just a few weeks before the start of the first Republican primary debate for the 2016 United States presidential election.[4][7]

The term, as well as the shortened form "cuck" for cuckold, originated on websites such as 4chan (specifically the /pol/ imageboard) and 8chan, the right-wing message board My Posting Career,[1][3] the blog The Right Stuff,[8] and other sites in the alt-right movement.[3][9][10]''')

        self.menubar = tk.Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu=self.menubar)
        self.s = 1
        self.x2 = 50
        self.y2 = 0
        self.running = True

    def value_to_y(self, val):
        return 550 - 5 * val

    def step(self, newY):
        if self.running:
            if self.s == 23:
                # new frame
                self.s = 1
                self.x2 = 50
                self.Canvas1.delete('temp')  # only delete items tagged as temp
            x1 = self.x2
            y1 = self.y2
            self.x2 = 50 + self.s * 50
            self.y2 = self.value_to_y(newY)
            self.Canvas1.create_line(x1, y1, self.x2, self.y2, fill='blue', tags='temp')
            self.s = self.s + 1
            self.Canvas1.after(300, self.step)

    def pause(self):
        if self.running:
            self.running = False
        else:
            self.running = True


if __name__ == '__main__':
    vp_start_gui()



